plt.figure(dpi=800, figsize=(5,2))
plt.plot(np.arange(320)+max_iter-320, lambda_320_ave, label='320 Iterations', ls='-', color='gray', lw=0.9)
plt.fill_between(np.arange(320)+max_iter-320, lambda_320_min, lambda_320_max, color='gray', alpha=0.2, linewidth=0)
plt.plot(np.arange(160)+max_iter-160, lambda_160_ave, label='160 Iterations', ls='-', color='purple', lw=0.9)
plt.axvline(x=max_iter-160, ls='-.', color='purple')
plt.fill_between(np.arange(160)+max_iter-160, lambda_160_min, lambda_160_max, color='purple', alpha=0.2, linewidth=0)
plt.plot(np.arange(80)+max_iter-80, lambda_80_ave, label='80 Iterations', ls='-', color='orange', lw=0.9)
plt.axvline(x=max_iter-80, ls='-.', color='orange')
plt.fill_between(np.arange(80)+max_iter-80, lambda_80_min, lambda_80_max, color='orange', alpha=0.2, linewidth=0)
plt.plot(np.arange(40)+max_iter-40, lambda_40_ave, label='40 Iterations', ls='-', color='green', lw=0.9)
plt.axvline(x=max_iter-40, ls='-.', color='green')
plt.fill_between(np.arange(40)+max_iter-40, lambda_40_min, lambda_40_max, color='green', alpha=0.2, linewidth=0)
plt.plot(np.arange(20)+max_iter-20, lambda_20_ave, label='20 Iterations', ls='-', color='blue', lw=0.9)
plt.axvline(x=max_iter-20, ls='-.', color='blue')
plt.fill_between(np.arange(20)+max_iter-20, lambda_20_min, lambda_20_max, color='blue', alpha=0.2, linewidth=0)
plt.plot(np.arange(10)+max_iter-10, lambda_10_ave, label='10 Iterations', ls='-', color='red', lw=0.9)
plt.axvline(x=max_iter-10, ls='-.', color='red')
plt.fill_between(np.arange(10)+max_iter-10, lambda_10_min, lambda_10_max, color='red', alpha=0.2, linewidth=0)
